resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/janus/operator
  newTag: v0.0.1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - default-config/deployment.yaml
  - default-config/service.yaml
  - default-config/route.yaml
  - default-config/db-statefulset.yaml
  - default-config/db-service.yaml
  - default-config/db-service-hl.yaml
  - default-config/db-secret.yaml
  - default-config/backend-auth-configmap.yaml
  - default-config/dynamic-plugins.yaml
  - default-config/app-config.yaml
  - default-config/secret-envs.yaml
  #- default-config/configmap-files.yaml
  #- default-config/configmap-envs.yaml
  #- default-config/seret-files.yaml
  name: default-config
