apiVersion: v1
kind: Service
metadata:
  name: backstage-psql-cr1-hl # placeholder for 'backstage-psql-<cr-name>-hl'
spec:
  selector:
    backstage.io/app:  backstage-psql-cr1 # placeholder for 'backstage-psql-<cr-name>'
  clusterIP: None
  ports:
    - port: 5432