apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_PASSWORD: admin123
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRESQL_ADMIN_PASSWORD: admin123
  POSTGRES_HOST: bs1-db-service    #placeholder <crname>-db-service