apiVersion: v1
kind: Secret
metadata:
  name: # placeholder for 'backstage-psql-secret-<cr-name>'
stringData:
  "POSTGRES_PASSWORD": "rl4s3Fh4ng3M4" # default value, change to your own value
  "POSTGRES_PORT": "5432"
  "POSTGRES_USER": "postgres"
  "POSTGRESQL_ADMIN_PASSWORD": "rl4s3Fh4ng3M4" # default value, change to your own value
  "POSTGRES_HOST": "" # set to your Postgres DB host. If the local DB is deployed, set to 'backstage-psql-<cr-name>'
